//REGISTER A USER
POST http://localhost:2828/user-api/user
Content-Type: application/json

{
  "userId":800,
  "email":"abcd@westagilelabs.com",
  "username":"abcd",
  "password":"abcd"
}

###SUPER ADMIN MAPPING USER TO ROLE
PUT http://localhost:2828/superAdmin-api/user/role
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwMCwidXNlclJvbGUiOiJzdXBlckFkbWluIiwiaWF0IjoxNjc4NjgzMTg4LCJleHAiOjE2Nzg3Njk1ODh9.n3IIAI0AmX9DaZTGH8PE3KMBORliLN7Spa0b8D0u4EY
Content-Type: application/json

{
  "userId":600,
  "role":"front end" 
}

###USER LOGIN
POST http://localhost:2828/user-api/user/login
Content-Type: application/json

{
    "userId":300,
	"password":"pavani"
}

###FORGOT PASSWORD TRIGGER A EMAIL
POST http://localhost:2828/user-api/forget-password
Content-Type: application/json

{
    "email":"dayyubiddika@gmail.com"
}

###RESET PASSWORD
POST http://localhost:2828/user-api/reset-password/email/dayyubiddika@gmail.com
Content-Type: application/json

{
    "otp":539012,
    "password":"dayyuharsha"
}

### GET SUPER ADMIN
GET http://localhost:2828/superAdmin-api/superadmin
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwMCwidXNlclJvbGUiOiJzdXBlckFkbWluIiwiaWF0IjoxNjc4Njg3NjM4LCJleHAiOjE2Nzg3NzQwMzh9.ySqv2QTrlLEJuDMeIIMyT_5oAsojhjuLHmMtgEcgfFk


###ADMIN CREATE THE PROJECT AND ASSIGN GDO, PROJECTMANAGER AND HRMANAGER TO THE PROJECT
POST http://localhost:2828/admin-api/admin/project
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIwMCwidXNlclJvbGUiOiJBZG1pbiIsImlhdCI6MTY3ODYwMjc3NywiZXhwIjoxNjc5NDY2Nzc3fQ.BMiczs6ZFiDxsLbqSBAOG0mjJmnArvmA1qG18wgtj2U
Content-Type: application/json

{
  "projectId":1,
  "projectName":"backend project",
  "client":3000,
  "gdoId":100,
  "projectManager":400,
  "hrManager":500,
  "clientAccountManager":"jahnavi",
  "statusOfProject":"on going",
  "startDate":"2023/10/31",
  "endDate":"2023/12/30",
  "overAllProjectFitnessIndicator":"Green",
  "domain":".net",
  "typeOfProject":"Development"
}


###GET ALL PROJECTS BY CLICKING ON PORTFOLIO DASHBOARD
GET http://localhost:2828/admin-api/admin/portfolioDashboard
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIwMCwidXNlclJvbGUiOiJBZG1pbiIsImlhdCI6MTY3ODYwMjcxNCwiZXhwIjoxNjc5NDY2NzE0fQ.o7TxZYGpDeEYQEhfLoh9aKx4LNnRFLwYcZCvmXYJCkk

###GET SPECIFIC PROJECT DETAILS BY CLICKING ON SPECIFIC PROJECT FROM PORFOLIO DASHBOARD
GET http://localhost:2828/admin-api/admin/portfolioDashboard/1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIwMCwidXNlclJvbGUiOiJBZG1pbiIsImlhdCI6MTY3ODYwMjcxNCwiZXhwIjoxNjc5NDY2NzE0fQ.o7TxZYGpDeEYQEhfLoh9aKx4LNnRFLwYcZCvmXYJCkk


### FOR GDO LOGIN

###GET ALL PROJECTS UNDER GDO MAINTANANCE
GET http://localhost:2828/gdo-api/100/portfolioDashboard 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMwMCwidXNlclJvbGUiOiJHRE8gaGVhZCIsImlhdCI6MTY3ODYwMzE1MywiZXhwIjoxNjc5NDY3MTUzfQ.nbaf1NX_JH5xVtyV8DbAYxor1EBeAClu1qW2IpqaTFc

###GET SPECIFIC PROJECT DETAILS BY CLICKING ON SPECIFIC PROJECT FROM PORFOLIO DASHBOARD
GET http://localhost:2828/gdo-api/100/portfolioDashboard/2
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMwMCwidXNlclJvbGUiOiJHRE8gaGVhZCIsImlhdCI6MTY3ODYwMzMwMiwiZXhwIjoxNjc5NDY3MzAyfQ.IznuQ38DhnLQdiFTiJGt1rcQtYc2yxApCn19hVhH0zU 


### ASSIGN PROJECT TO AN EMPLOYEE BY GDO
POST http://localhost:2828/gdo-api/gdo/projectTeam
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMwMCwidXNlclJvbGUiOiJHRE8gaGVhZCIsImlhdCI6MTY3ODcwNzQ5NCwiZXhwIjoxNjc4NzkzODk0fQ.jkXHfBbTgv_DClaY5wP9DDbMWg2lGBWmAsfjYzfIXwc
Content-Type: application/json

{
  "empId":600,
  "projectId":2,
  "username":"venky",
  "role":"tester",
  "startDate":"2023/03/08",
  "endDate":"2023/07/23",
  "status":"In Progress",
  "billingStatus":"billed",
  "exposedToCustomer":"yes",
  "allocationType":"permanent" 
}

###GET PROJECTS USING PROJECT ID
GET http://localhost:2828/gdo-api/gdo/2/get-projects
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMwMCwidXNlclJvbGUiOiJHRE8gaGVhZCIsImlhdCI6MTY3ODcwNzQ5NCwiZXhwIjoxNjc4NzkzODk0fQ.jkXHfBbTgv_DClaY5wP9DDbMWg2lGBWmAsfjYzfIXwc

### GET ALL PROJECTS
GET http://localhost:2828/gdo-api/gdo/get-projects
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMwMCwidXNlclJvbGUiOiJHRE8gaGVhZCIsImlhdCI6MTY3ODcwNzQ5NCwiZXhwIjoxNjc4NzkzODk0fQ.jkXHfBbTgv_DClaY5wP9DDbMWg2lGBWmAsfjYzfIXwc

###RAISE RESOURCING REQUEST BY GDO
POST http://localhost:2828/gdo-api/gdo/resourcingRequest
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMwMCwidXNlclJvbGUiOiJHRE8gaGVhZCIsImlhdCI6MTY3ODYwMzQ2OSwiZXhwIjoxNjc5NDY3NDY5fQ.9QKXuVHboZcf7KVpAwXZ9VWNAGPliPD3-72XkcghI9o
Content-Type: application/json

{
  "gdoId" :100,
  "projectId":2,
  "requestDescription":"takes time to complete"
}

###FOR PROJECT MANAGER LOGIN

###PROJECT UPDATES BY PROJECT MANAGER
POST http://localhost:2828/projectManager-api/projectManager/projectUpdates
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQwMCwidXNlclJvbGUiOiJwcm9qZWN0IG1hbmFnZXIiLCJpYXQiOjE2Nzg2MDM3ODksImV4cCI6MTY3OTQ2Nzc4OX0.2lBWs_edrlnQLTxhvphcbf6tQQkVuMGVo7B7-BW2_co
Content-Type: application/json

{
  "projectId":1,
  "projectManager":400,
  "date":"2023/04/20",
  "projectStatusUpdate":"New feature updated",
  "scheduleStatus":"Red",
  "resourcingStatus":"Green",
  "qualityStatus":"Green",
  "waitingForClient":"no"
}

###RAISE PROJECT CONCERN BY PROJECT MANAGER
POST http://localhost:2828/projectManager-api/projectManager/projectConcern
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQwMCwidXNlclJvbGUiOiJwcm9qZWN0IG1hbmFnZXIiLCJpYXQiOjE2Nzg2MDM5MTUsImV4cCI6MTY3OTQ2NzkxNX0.LA0359HmbwER05cSQ37B0xw69qH9qRCdYLxF9rIjjuk
Content-Type: application/json

{
  "projectId":1,
  "projectManager":400,
  "concernDescription":"don't have enough time",
  "concernRaisedBy":"kalavathi",
  "onDate":"2023/07/10",
  "severity":"Abnormal",
  "raisedInternallyOrNot":"Yes",
  "statusOfConcern":"pending",
  "concernMitigatedOnDate":"2023/08/15"
}

###GET ALL PROJECTS UNDER PROJECTMANAGER
GET http://localhost:2828/projectManager-api/400/portfolioDashboard
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQwMCwidXNlclJvbGUiOiJwcm9qZWN0IG1hbmFnZXIiLCJpYXQiOjE2Nzg2MDM5ODEsImV4cCI6MTY3OTQ2Nzk4MX0.JGATVIQoHBdgrUpheLYikFQNOLMfzreu2ka7x4AMwlw

###GET DETAILED PROJECTS DETAILS UNDER PROJECTMANAGER FOR SPECIFIC PROJECT
GET http://localhost:2828/projectManager-api/projectManager/portfolioDashboard/2
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQwMCwidXNlclJvbGUiOiJwcm9qZWN0IG1hbmFnZXIiLCJpYXQiOjE2Nzg2MDM5ODEsImV4cCI6MTY3OTQ2Nzk4MX0.JGATVIQoHBdgrUpheLYikFQNOLMfzreu2ka7x4AMwlw

###DELETE PROJECT BASED ON PROJECTID BY ADMIN
DELETE http://localhost:2828/admin-api/admin/project/1

###RAISE PROJECT CONCERNS AND TRIGGER A EMAIL
POST http://localhost:2828/projectManager-api/projectId/2/raise-project-concern
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMwMCwidXNlclJvbGUiOiJHRE8gaGVhZCIsImlhdCI6MTY3ODY5NjczMiwiZXhwIjoxNjc4NzgzMTMyfQ.m642Qtc8ZCYABjY3BQTWG7EenSY40vq30mn36xnF178

{
  "projectId":2,
  "concernDescription":"More systems required",
  "raisedBy":"likki@westagilelabs.com",
  "raisedOnDate":"2023/03/04",
  "severity":"Critical",
  "concernRaisedInternallyOrNot":true,
  "status":"pending",
  "mitigatedOn":"2023/03/06"
}

###UPDATE PROJECT BASED ON PROJECT ID BY PROJECT MANAGER
PUT http://localhost:2828/projectManager-api/projectId/2/update-project
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQwMCwidXNlclJvbGUiOiJwcm9qZWN0IG1hbmFnZXIiLCJpYXQiOjE2Nzg2OTk2NTUsImV4cCI6MTY3ODc4NjA1NX0.NbepJ1P2HZRTrgZct4v1aTNa4wDMxWaJxwCq8e8-vQ4
Content-Type: application/json

{
    "projectId":2,
    "projectName":"full stack project"
}

###UPDATE PROJECT BY ADMIN
PUT http://localhost:2828/admin-api/admin/project/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIwMCwidXNlclJvbGUiOiJBZG1pbiIsImlhdCI6MTY3ODcwMDIzOCwiZXhwIjoxNjc4Nzg2NjM4fQ.FMqd4ho392N0juU598oYJ7DhocoV8D9U9R_2LSSQAyc
Content-Type: application/json

{
    "projectId":1,
    "projectName":"project pulse"
}

###UPDATE CONCERN BY PROJECT MANAGER
PUT http://localhost:2828/projectManager-api/projectManager/2/update-concerns
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQwMCwidXNlclJvbGUiOiJwcm9qZWN0IG1hbmFnZXIiLCJpYXQiOjE2Nzg3MDExNDYsImV4cCI6MTY3ODc4NzU0Nn0.6ceRndbdCmRCZmucs4zmtCmo66zWrbfcFoK3Prqb6a8
Content-Type: application/json

{
    "projectId":2,
    "concernDescription":"needed some more time manual power to complete"
}

###DELETE CONCERN BY PROJECT MANAGER
DELETE http://localhost:2828/projectManager-api/projectManager/1/delete-concern
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQwMCwidXNlclJvbGUiOiJwcm9qZWN0IG1hbmFnZXIiLCJpYXQiOjE2Nzg3MDExNDYsImV4cCI6MTY3ODc4NzU0Nn0.6ceRndbdCmRCZmucs4zmtCmo66zWrbfcFoK3Prqb6a8

###UPDATING PROJECT UPDATES
PUT http://localhost:2828/projectManager-api/projectManager/2/update
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQwMCwidXNlclJvbGUiOiJwcm9qZWN0IG1hbmFnZXIiLCJpYXQiOjE2Nzg3MDExNDYsImV4cCI6MTY3ODc4NzU0Nn0.6ceRndbdCmRCZmucs4zmtCmo66zWrbfcFoK3Prqb6a8
Content-Type: application/json

{
    "projectId":2,
    "projectStatusUpdate":"New feature updated"
}

###DELETE PROJECT UPDATES
DELETE http://localhost:2828/projectManager-api/projectManager/2/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQwMCwidXNlclJvbGUiOiJwcm9qZWN0IG1hbmFnZXIiLCJpYXQiOjE2Nzg3MDExNDYsImV4cCI6MTY3ODc4NzU0Nn0.6ceRndbdCmRCZmucs4zmtCmo66zWrbfcFoK3Prqb6a8




